export default[
  {
    "_id": "123",
    "username": "jedi_master",
    "password": "yoda123",
    "firstName": "Yoda",
    "lastName": "",
    "email": "yoda@jedi.com",
    "dob": "896-08-29",
    "role": "FACULTY",
    "loginId": "SW001JEDI",
    "section": "SW101",
    "lastActivity": "2020-12-10",
    "totalActivity": "31:12:25"
  },
  {
    "_id": "234",
    "username": "sith_lord",
    "password": "vader123",
    "firstName": "Darth",
    "lastName": "Vader",
    "email": "vader@sith.com",
    "dob": "41.9BBY",
    "role": "STUDENT",
    "loginId": "SW002SITH",
    "section": "SW101",
    "lastActivity": "2020-11-16",
    "totalActivity": "25:41:32"
  },
  {
    "_id": "345",
    "username": "rebel_leader",
    "password": "leia123",
    "firstName": "Leia",
    "lastName": "Organa",
    "email": "leia@rebel.com",
    "dob": "19BBY-05-22",
    "role": "TA",
    "loginId": "SW003REB",
    "section": "SW101",
    "lastActivity": "2020-11-21",
    "totalActivity": "18:53:21"
  },
  {
    "_id": "456",
    "username": "smuggler",
    "password": "solo123",
    "firstName": "Han",
    "lastName": "Solo",
    "email": "han@falcon.com",
    "dob": "29BBY-07-05",
    "role": "STUDENT",
    "loginId": "SW004SMUG",
    "section": "SW101",
    "lastActivity": "2020-11-02",
    "totalActivity": "14:22:33"
  },
  {
    "_id": "567",
    "username": "protocol_droid",
    "password": "c3po123",
    "firstName": "C-3PO",
    "lastName": "",
    "email": "c3po@droid.com",
    "dob": "112BBY",
    "role": "STUDENT",
    "loginId": "SW005PROT",
    "section": "SW101",
    "lastActivity": "2020-12-15",
    "totalActivity": "22:33:44"
  },
  {
    "_id": "678",
    "username": "astromech",
    "password": "r2d2123",
    "firstName": "R2",
    "lastName": "D2",
    "email": "r2d2@droid.com",
    "dob": "33BBY",
    "role": "FACULTY",
    "loginId": "SW006ASTR",
    "section": "SW101",
    "lastActivity": "2020-12-20",
    "totalActivity": "44:33:22"
  },
  {
    "_id": "890",
    "username": "chosen_one",
    "password": "skywalker123",
    "firstName": "Luke",
    "lastName": "Skywalker",
    "email": "luke@jedi.com",
    "dob": "19BBY-05-25",
    "role": "TA",
    "loginId": "SW007CHOS",
    "section": "SW101",
    "lastActivity": "2020-12-04",
    "totalActivity": "12:23:34"
  },
  {
    "_id": "777",
    "username": "bounty_hunter",
    "password": "fett123",
    "firstName": "Boba",
    "lastName": "Fett",
    "email": "boba@bounty.com",
    "dob": "32BBY-07-15",
    "role": "STUDENT",
    "loginId": "SW008BNTY",
    "section": "SW101",
    "lastActivity": "2020-10-11",
    "totalActivity": "21:32:43"
  },
  {
    "_id": "888",
    "username": "republic_chancellor",
    "password": "palpatine123",
    "firstName": "Sheev",
    "lastName": "Palpatine",
    "email": "palpatine@republic.com",
    "dob": "84BBY-12-15",
    "role": "ADMIN",
    "loginId": "SW009REP",
    "section": "SW101",
    "lastActivity": "2020-12-27",
    "totalActivity": "41:32:43"
  }
];
